// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCulS6yPlIgHJylM6cQL_8Xn0jqvDmBAh4',
    appId: '1:262895451895:web:76783f7d41bc4e234f1df2',
    messagingSenderId: '262895451895',
    projectId: 'newapp-7204d',
    authDomain: 'newapp-7204d.firebaseapp.com',
    storageBucket: 'newapp-7204d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOxrzfcMYl34FkI6ldjqyy_EndN90_hE',
    appId: '1:262895451895:android:895c69ed3517e6564f1df2',
    messagingSenderId: '262895451895',
    projectId: 'newapp-7204d',
    storageBucket: 'newapp-7204d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMutFRltTzlfs5-D3j24hlO8EZABGemMw',
    appId: '1:262895451895:ios:1c6a9afb19186dec4f1df2',
    messagingSenderId: '262895451895',
    projectId: 'newapp-7204d',
    storageBucket: 'newapp-7204d.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMutFRltTzlfs5-D3j24hlO8EZABGemMw',
    appId: '1:262895451895:ios:1c6a9afb19186dec4f1df2',
    messagingSenderId: '262895451895',
    projectId: 'newapp-7204d',
    storageBucket: 'newapp-7204d.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCulS6yPlIgHJylM6cQL_8Xn0jqvDmBAh4',
    appId: '1:262895451895:web:312be50084b627e74f1df2',
    messagingSenderId: '262895451895',
    projectId: 'newapp-7204d',
    authDomain: 'newapp-7204d.firebaseapp.com',
    storageBucket: 'newapp-7204d.appspot.com',
  );
}
